### ISSUE TITLE
Improvements/roadmap

### ISSUE THREAD

**Issue by continentaldivide** [continentaldivide/redborderchest.com#1]
## Todo

- [ ] Rebuild site with react
- [ ] Facelift / overhaul styling
- [ ] Add accessibility
- [ ] Re-source Hive symbol assets
- [ ] Redesign for mobile-friendliness
- [ ] Number symbols/instructions
- [ ] Add images of locations?
- [ ] Add VotD red border chest guide
